### PR TITLE
Fix helm repo

### PR DESCRIPTION
**Pull request by varac**
This PR adds latest packaged wekan chart 1.1.0 and a helm repo index.yaml file, so you can add the helm repo afterwards by

    helm repo add wekan https://wekan.github.io/charts

### CODE REVIEW

**Comment by varac** [comment]
I also removed the chart source in this repo since you said you would like to maintain the chart in https://github.com/wekan/wekan.
Whenever you want to publish a new chart you need to do the following: 

# In wekan.git (master branch)

* Increase the (chart) `version` number in `helm/wekan/Chart.yaml`

# In charts.git (gh-pages branch)

    helm package ../wekan.git/helm/wekan
    helm repo index . --url https://wekan.github.io/charts

You should also remove the charts.git `main` branch since it's not used for anything. Then you can either rename the `gh-pages` branch to `main`, and configure gh-pages to use the `main` branch, or just live without the `main` branch and make the `gh-pages` branch the default one.

**Comment by varac** [comment]
About publishing on artifact hub: Lets first merge this and make sure you have a valid helm repo which you can add with helm, and then take care about publishing on artifact hub later

**Comment by varac** [comment]
@xet7 Hej, are you around for reviewing ? Anything else you need ?

**Comment by xet7** [comment]
@varac 

I'm usually around every day. I'm watching at GitHub all WeKan repos etc so I get all new issues, comments etc as email notifications.

**Comment by xet7** [comment]
@varac 

Oops, it seems this PR was already made 7 days ago. It seems I did not notice it previously. I get about 100 new messages every day, so this could happen.

**Comment by varac** [comment]
Yeah, it works now!

```
$ helm repo add wekan https://wekan.github.io/charts
"wekan" has been added to your repositories

$ helm repo update         
Hang tight while we grab the latest from your chart repositories...
..Successfully got an update from the "wekan" chart repository

$ helm search repo wekan
NAME       	CHART VERSION	APP VERSION	DESCRIPTION       
wekan/wekan	1.1.0        	5.83       	Open Source kanban
```

**Comment by varac** [comment]
Next step would be: https://github.com/wekan/wekan/issues/4051

**Comment by varac** [comment]
>  You should also remove the charts.git main branch since it's not used for anything. Then you can either rename the gh-pages > branch to main, and configure gh-pages to use the main branch, or just live without the main branch and make the gh-pages  > branch the default one.

@xet7 what do you think ?

**Comment by xet7** [comment]
@varac 

Currently update version numbers both at https://github.com/wekan/wekan and https://github.com/wekan/charts . AFAIK charts repo is currently used to show gh-pages at https://wekan.github.io/charts/ . Does something at ArtifactHub not work currently? Or why change? If something is needed, someone can send PR.

**Pull request merged**
