### PR TITLE
Support k8s >= 1.22 ingress API

### PR DESCRIPTION
**Pull request by varac**
https://kubernetes.io/blog/2021/08/04/kubernetes-1-22-release-announcement/#removal-of-several-deprecated-beta-apis

    
        ❯ helm lint .
        ==> Linting .
        [WARNING] templates/ingress.yaml: networking.k8s.io/v1beta1 Ingress is deprecated in v1.19+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
    
        1 chart(s) linted, 0 chart(s) failed

### CODE REVIEW

**Comment by varac** [comment]
This is *needed* in k8s 1.22, and compatible with version >=1.19

**Comment by varac** [comment]
Ready for review!

**Comment by varac** [comment]
Oh noes, this is so confusing. I submitted my PR to this repo, but we use the helm chart from https://github.com/wekan/wekan/tree/master/helm/wekan. Please consolidate this / maintain only one helm chart (and delete the other one), otherwise they will diverge.

I know you're in the process of publishing the [helm chart to artifacthub](https://github.com/wekan/wekan/issues/4051), hope you'll get it done soon :crossed_fingers:

**Comment by varac** [comment]
@xet7  So which location will recieve updates from your point of view ?

**Comment by xet7** [comment]
@varac 

I know nothing about helm. And I don't know what repo to add to artifacthub and how. Pull requests etc info very welcome.

I wish having all at https://github.com/wekan/wekan could be setup somehow.

**Comment by varac** [comment]
@xet7 I created https://github.com/wekan/charts/pull/3 to fix the helm repo

**Pull request merged**
